name: Terraform CI/CD ETE2025

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Recup du repository
        uses: actions/checkout@v4


      - name: Installation Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: '1.10.4'


      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Create terraform.tfvars
        run: |
          echo "dbpassword = \"${{ secrets.DB_PASSWORD }}\"" > terraform.tfvars
          echo "dbusername = \"${{ secrets.DB_USERNAME }}\"" >> terraform.tfvars
          
      - name: Create EC2 Key Pair
        run: |
          echo "${{ secrets.ECF_KEY_PUBLIC }}" > ecfkey.pub
      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: success()
        run: terraform apply -auto-approve tfplan
